# Generated by Django 2.2.2 on 2021-07-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.FileField(default=0, upload_to='', verbose_name='用户角色'),
        ),
    ]
