# Generated by Django 2.2.2 on 2021-07-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default=0, max_length=1, verbose_name='用户角色'),
        ),
    ]
