# Generated by Django 2.2.2 on 2021-07-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210701_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='desc',
            field=models.TextField(default='', verbose_name='个人简介'),
        ),
    ]
