# Generated by Django 2.2.2 on 2021-07-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=20, verbose_name='书名')),
                ('product', models.CharField(max_length=20, verbose_name='出版社')),
                ('principal', models.CharField(max_length=20, verbose_name='负责人')),
                ('book_index', models.CharField(max_length=30, verbose_name='图书索引')),
                ('ISBN', models.CharField(max_length=40, verbose_name='ISBN号')),
                ('img', models.CharField(max_length=1024, verbose_name='图书封面路径')),
            ],
            options={
                'verbose_name': '图书',
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='分类名称')),
            ],
            options={
                'verbose_name': '图书分类',
                'db_table': 'category',
            },
        ),
    ]
