# Generated by Django 2.2.2 on 2021-07-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category_id',
            field=models.IntegerField(default=5, max_length=20, verbose_name='分类id'),
        ),
    ]
